### ISSUE TITLE
looking to help

### ISSUE THREAD

**Issue by kevupton** [mvrahden/reinforce-js#3]
Hey Dude,
Love the implementation, 
Need any help with this ?

**Comment by kevupton** [comment]
code implementation is very readable, well done. so much more readable then karpathy xD

**Comment by kevupton** [comment]
Also what is the point of `width` and height` on the `Env` ?

**Comment by mvrahden** [comment]
Hey @kevupton,

Thank you very! I appreciate your words :)

to answer your last question first: the properties `height` and `width` are defining the width and height of the environment space for use cases of the TD-Solver, to verify whether an action is allowed to be performed or not.
This is kind of a weakness of my attempt to create a unified abstraction hierarchy. Since the DQN-Solver doesn't make use of these information. Basically it's a design flaw at the moment. Feel free to refactor this :) The TD-Solver didn't got much care till now. I focused my work mainly on the DQN-Solver.

To answer your first question: sure, feel free to develop this further! I can add you as a collaborator if you feel like. I'd be happy to see some development in here. Since I placed a lot of effort and it would be sad to just let it rot in here.
I also don't have a well defined road map for this, so basically you can be very creative about the future path of this. Like adding new solvers from other research groups than Deepmind for example. Just to give you an idea :)

Let me know what you think about it

**Comment by kevupton** [comment]
If you want to make me a collab, that would be awesome! 
Ill make some PR's for you to check out

**Comment by mvrahden** [comment]
Sounds good!
Make sure to also check out the [recurrent-js](https://github.com/mvrahden/recurrent-js) repository, which provides the neural networks for the DQN-Solver ;)
Cheers
